import Setup from "../components/Setup";
import "../../../styles/globals.css";
import React from "react";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import Navbar from "../components/Navbar";

export const metadata = {
    title: "Next.js",
    description: "Generated by Next.js",
};

export default async function RootLayout({
                                             children,
                                             params: asyncParams,
                                         }: Readonly<{
    children: React.ReactNode;
    params: Promise<{ locale: string }>;
}>) {
    const params = await asyncParams;
    const { locale } = params;

    const messages = await getMessages();
    return (
        <html lang={locale}>
        <body>
        <NextIntlClientProvider messages={messages}>
            <Setup>
                <nav>
                    <Navbar />
                </nav>
                {children}
            </Setup>
        </NextIntlClientProvider>
        </body>
        </html>
    );
}
