import { NextIntlClientProvider } from "next-intl";
import Setup from "../../components/Setup";
import React from "react";
import { getMessages } from "next-intl/server";
import "../../../../styles/globals.css";

export const metadata = {
    title: "Next.js",
    description: "Generated by Next.js",
};

export default async function RootLayout({
    children,
    params: asyncParams,
}: Readonly<{
    children: React.ReactNode;
    params: Promise<{ locale: string }>;
}>) {
    const messages = await getMessages();
    const params = await asyncParams;
    const { locale } = params;

    return (
        <html lang={locale} className={"h-full bg-light-bg dark:bg-dark-bg p-4"}>
            <body>
                <NextIntlClientProvider messages={messages}>
                    <Setup>{children}</Setup>
                </NextIntlClientProvider>
            </body>
        </html>
    );
}
